tasks:
  - init: ./services create
    command: |
      ./services start
      docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 
      docker exec fiware-orion curl http://localhost:1026/version
      docker logs -f fiware-orion-proxy

ports:
  - port: 1026
    onOpen: ignore
    visibility: public
  - port: 1027
    onOpen: ignore
    visibility: public
  - port: 3001
    onOpen: ignore
    visibility: public
  - port: 3306
    onOpen: ignore
    visibility: public
  - port: 4041
    onOpen: ignore
    visibility: public
  - port: 7896
    onOpen: ignore
    visibility: public
  - port: 7897
    onOpen: ignore
    visibility: public
  - port: 27017
    onOpen: ignore
    visibility: public
  - port: 1880
    onOpen: open-browser
    visibility: public
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3005
    onOpen: open-browser
    visibility: public
  - port: 8081
    onOpen: open-preview
    visibility: public
