#!/bin/bash
#
#  Command Line Interface to start all services associated with the Getting-Started Tutorial
#
#  For this tutorial the commands are merely a convenience script to run docker-compose
#

set -e

loadData () {
	echo "Loading context data"
	./import-data
	echo "Provisioning IoT devices"
	./provision-devices
}

if (( $# != 1 )); then
    echo "Illegal number of parameters"
    echo "usage: services [create|start|stop]"
    exit 1
fi

command="$1"
case "${command}" in
	"help")
        echo "usage: services [create|start|stop]"
        ;;
    "start")
		echo -e "Starting six containers \033[1;34mOrion\033[0m, \033[1;36mIoT-Agent\033[0m,\033[1;31mKeyrock\033[0m, \033[1;30mContext-Provider\033[0m and \033[1;30mMongoDB\033[0m and \033[1;30mMySQL\033[0m databases."
		echo -e "- \033[1;34mOrion\033[0m is the context broker"
		echo -e "- \033[1;36mIoT-Agent\033[0m is configured for the UltraLight Protocol"
		echo -e "- \033[1;30mContext-Provider\033[0m acts as a series of dummy IoT Sensors over HTTP"
		echo -e "- \033[1;31mKeyrock\033[0m is an Identity Management Front-End"
		echo ""
		docker-compose --log-level ERROR -p fiware up -d --remove-orphans
		#loadData
		echo ""
		echo -e "Now open \033[4mhttp://localhost:3000\033[0m"
		;;
	"stop")
		echo "stopping containers"
		docker-compose --log-level ERROR -p fiware down -v --remove-orphans

		;;
	"create")
		echo "Obtaining MySQL image"
		docker pull mysql:5.7
		echo "Obtaining Latest Keyrock Image"
		docker pull fiware/fiware-idm
		;;
	*)
		echo "Command not Found."
		echo "usage: services [create|start|stop]"
		exit 127;
		;;
esac



