routes:
  - id: 1
    uri: /*
    upstream_id: 1
    plugins:
      forward-auth:
        uri: http://auth-service:5000/auth
        request_headers:
          - Authorization
        client_headers: []
        upstream_headers: []
        timeout: 3000
        keepalive: true
        keepalive_pool_size: 5
        keepalive_timeout: 60000
        ssl_verify: false
        allow_degradation: false

upstreams:
  - id: 1
    type: roundrobin
    nodes:
      "orion:1026": 1
#END
