
name: "CI"
on:
  push:
    branches:
      - master
      - NGSI-v2
      - NGSI-LD
  pull_request:
    branches:
      - master
      - NGSI-v2
      - NGSI-LD
  workflow_dispatch:

jobs:
  test-modules:
    name: Test Script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0
        submodules: recursive
    - name: Build Images
      run: |
        ./services create || true
    - name: Start Services
      run: |
        ./services start
    - name: Run RBAC Smoke Test
      run: |
        chmod +x .github/test/rbac_smoke_test
        ./.github/test/rbac_smoke_test
    - name: Stop Services
      if: always()
      run: |
        ./services stop
